# Generated by Django 3.1.5 on 2021-01-15 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catergory',
            options={'verbose_name_plural': 'Catergories'},
        ),
    ]
